sudo: required
language: python

python:

  - "3.6"

services:
  - docker

before_install:
- ./.travis/main.sh  

install:
  - pip install boto3

script: 

  - python app/app.py
  - make test
  - make image

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make push-image ;

# don't notify me when things fail
notifications:
  email: false
