sudo: required
language: python

python:

  - "3.6"

services:
  - docker

before_install:
  - docker build -t idanharu/superup-test .
  - docker run -d -p 5000:80 idanharu/superup-test
#  - docker ps -a
#  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"
#
install:
  - pip install boto3

script:
  - 

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker push idanharu/superup-test
  on:
    branch: master
