sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t idanharu/superup-test .
  - docker run -d -p 5000:80 idanharu/superup-test
#  - docker ps -a
#  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

#script:
#  - bundle exec rake test

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
