sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t showsecret .
      - docker images
      - docker tag showsecret $DOCKER_USERNAME/superup-test
      - docker push $DOCKER_USERNAME/superup-test
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/superup-test
    - script: docker run --rm $DOCKER_USERNAME/superup-test
