sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script: docker build -t showsecret .
    - stage: test
      script: docker run --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY $DOCKER_USERNAME/superup-test
    - stage: deploy docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password$
      - docker images
      - docker tag showsecret $DOCKER_USERNAME/superup-test
      - docker push $DOCKER_USERNAME/superup-test

